### ISSUE TITLE
Patrocinio para meetup de septiembre

### ISSUE THREAD

**Issue by sierisimo** [GDLActivity/GDL-Meetup#1]
Estamos en el proceso de confirmar a Centraal para el meetup de septiembre.

**Comment by IsabelPalomar** [comment]
Entonces es centraal o es Luxoft?

**Comment by lalongooo** [comment]
Agarramos a uno para Septiembre y otro para Octubre.

**Comment by sierisimo** [comment]
Una vez mas estamos ante la situacion de tener lugar pero no tenemos para snacks. Centraal no pudo conseguir el patrocinio de los consumibles, solo podra prestarnos el espacio

**Comment by fercho1908** [comment]
cuanto es el promedio de dinero que se necesita?

**Comment by sierisimo** [comment]
Entre 2000 y 3000 pesotes

**Comment by DevOzcar** [comment]
el team 7eleven puede cooperar :v

**Comment by fercho1908** [comment]
Esta muy apresurada la fecha, pero intento solicitor patrocionio por parte de HCL :)

**Comment by lalongooo** [comment]
Shavos, acabo de hablar con Unosquare.
Solo nos ayudan si el evento es en las instalaciones de Unosquare... :(

**Comment by sierisimo** [comment]
@IsabelPalomar comento que veria con Sawyer si ellos podian salvarnos

**Comment by raul-aponte** [comment]
Novedades? si no para que @DevOzcar organice al team seven

**Comment by IsabelPalomar** [comment]
@raul-aponte ya les recorde a Sawyer, estoy esperando respuesta

**Comment by IsabelPalomar** [comment]
Confirmado! Sawyer patrocina el meetup de Septiembre! Moving to done

**Comment by sierisimo** [comment]
Awesome! Sawyer salio como el heroe de esta historia, muchas gracias @IsabelPalomar
