### ISSUE TITLE
Contactar a Francisco Solsona para platicar acerca de patrocinio de eventos

### ISSUE THREAD

**Issue by IsabelPalomar** [GDLActivity/GDL-Meetup#10]

**Comment by sierisimo** [comment]
@IsabelPalomar necesitamos ver esto tambien para la parte de Realm. Ayer platicando con Tatiana me menciono que ella anda tambien revisando con Google, pero no recorde este nombre, crees que sea el mismo?

**Comment by IsabelPalomar** [comment]
@sierisimo yo creo que si, la ultima vez que platique me dijo que le enviara correo, quiero preguntarle de eso y del devFest!
