### ISSUE TITLE
Staff para #RealmWorldTour

### ISSUE THREAD

**Issue by sierisimo** [GDLActivity/GDL-Meetup#12]

**Comment by sierisimo** [comment]
Se anunciara esta info en el meetup de Septiembre para contactar voluntarios.

**Comment by lalongooo** [comment]
¿Cuántas personas necesitamos y en qué actividades requeriremos ayuda?

**Comment by sierisimo** [comment]
Segun yo, no deberian ser mas de 10 personas, incluso menos.
Las actividades que tengo en mente por ahora son cuestiones de:

* Chequeo de sonido y proyeccion / gente encargada de los microfonos
* Gente recibiendo en la entrada o llevando registro de asistentes (asumo que Realm tambien tendra una o dos personas para esto)
* Quien ayude a acomodar todo y cargar/llevar cosas.

Ahora que lo pienso... tal vez no sea necesaria tanta gente.

**Comment by fercho1908** [comment]
Yo puedo apoyar con el punto 2 o el 3.

**Comment by DavidBarboza** [comment]
Puedo apoyar con el punto 1 y 3. Yo creo que con los voluntarios que fuimos presentados en el meetup se arma. Nomás ponernos de acuerdo quién hará qué.

**Comment by raul-aponte** [comment]
Simon, yo tambien puedo apoyar con cualquiera de los puntos, propongo que el meetup de Octubre sea un simulacro, para que cada quien tenga entendido en que estará apoyando.

**Comment by raul-aponte** [comment]
Entonces como quedamos en este puto? Tendremos que llegar antes para preparar algo?

**Comment by DavidBarboza** [comment]
Alguna cosa que haga falta o consideración a tomar? andaré ahi en Centraal temprano para cualquier cosa

**Comment by sierisimo** [comment]
Quedo acordado:

* Necesitamos 3 personas que lleguen antes para apoyarnos con los registros/accesos.
* Necesitamos 2 personas que nos ayuden a repartir Stickers y playeras.

Tratare de llegar desde las 6pm para agilizar la movida.

**Comment by fercho1908** [comment]
yo sin problemas puedo llegar antes de las 6 a centraal, estoy relativamente cerca, me llevo mi lap para culquier cosa que se pueda necesitar

**Comment by raul-aponte** [comment]
Ok, llego 5:30 para apoyar en los registros, o lo que necesiten.

**Comment by DavidBarboza** [comment]
Ahi andaré desde las 5:50 pm apoyando con los accesos, repartir playeras o lo que haga falta.

**Comment by IsabelPalomar** [comment]
Gracias a todos por su apoyo ❤️ 
Me lo voy a perder porque no pude conseguir los días libres en el trabajo. Enjoy! 😎

**Comment by lalongooo** [comment]
Llego antes de las 6pm.
