### ISSUE TITLE
Speakers meetup Octubre

### ISSUE THREAD

**Issue by lalongooo** [GDLActivity/GDL-Meetup#15]

**Comment by lalongooo** [comment]
Contactar a Rafa Jasso por el interesado en dar la platica para el mes de Octubre.

**Comment by sierisimo** [comment]
@dan-zx nos ha ayudado en el pasado con contenido ("_rox for android_" y "_64k maneras de dispararse en el pie_"). Esta tambien propuesto para octubre con una platica sobre **OkHttp**

* Nombre: **Daniel Pedraza**
* Tema/Platica: **OkHttp/TBD**
* Empresa/Comunidad: EPAM

**Comment by sierisimo** [comment]
Consegui otro speaker: 
* Nombre: **Ademar Alvez - Wizeline**
* Tema/Platica: **TBD**
* Empresa: Wizeline

**Comment by sierisimo** [comment]
Hable con los speakers, no tendran problema en moverse de fecha dado el evento de Realm, cierro el issue para pasarlo a Noviembre
