### ISSUE TITLE
Mayor empuje al evento de Realm

### ISSUE THREAD

**Issue by sierisimo** [GDLActivity/GDL-Meetup#19]
Necesitamos darle un mayor empuje al evento de Realm, para que sea un turbo exito.

Eso implica:

* Facebook
* Twitter
* Email
* Otras comunidades

**Comment by raul-aponte** [comment]
Ok, tenemos algún material para hacer publicidad? yo solo se que tengo que decirle a todo el mundo que se registre en:
https://www.eventbrite.com/e/realm-world-tour-guadalajara-tickets-37397624301

**Comment by sierisimo** [comment]
Isabel compartio un documento con algunos "slogan" o textos que podriamos usar, adicional a eso yo he estado usando la imagen del evento de EventBrite + el hashtag #RealmWorldTour

[Doc aca](https://docs.google.com/document/d/1xhaigdNegR6Y7v_VN7aF7W-5BBfNco3ppfEg6InHvsE/edit?usp=sharing)

**Comment by IsabelPalomar** [comment]
Email enviado a los registrados en splashthat:
Total de emails: 91
![email - splashthat.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598c8e37396433001fdde76d/125516c66e82c728ace21e0d46ed999b2a8ec3e4cffaaf4fa54ef880214733316546b3397f8fe62bab0021435a5646ff480e5c17f9fbdd2aa2b13c70890e5ae8806d5a75d42103eee9dc4be05ce36ade0d97bcae8b45cae93825e3838e4f3c160c1080f74f78.png)

**Comment by IsabelPalomar** [comment]
Como es un evento en el que falta un poco mas de un mes para que pase y no queremos que la gente lo olvide o no tener la cantidad suficiente de asistentes propongo lo siguiente: 

* Agregar información acerca de Realm en las redes sociales de GDLActivity y en nuestras redes sociales, para que mas gente se entere de que se trata Realm, esta información puede ser acerca de los nuevos videos de Realm o de Realm Academy for android https://academy.realm.io/section/android/ o React y publicarlo en el fb DevC circle de Guadalajara junto con la invitación al evento.
* A principios de Octubre preguntar a Realm cuantos registrados van.
* Publicar de nuevo el evento 2 semanas antes, 1 semana antes y 1 día antes (siempre hay gente que se le olvida registrarse y se registra a ultima hora)
* Si hay alguien que le guste escribir posts, podemos crear un medium de la comunidad y agregar uno relacionado a Realm, nuevamente con la invitación al evento.

Diganme cuales les hacen mas sentido y cuales podríamos realizar y cuales no.

**Comment by raul-aponte** [comment]
El punto 3 me parece bastante logico, tratare de llevarlo a cabo con la gente a la que ya le informe.

**Comment by sierisimo** [comment]
Me encanta la ultima idea, todas las demas, tratare de ver si @DavidBarboza y @fercho1908 que andan en la pagina de facebook nos pueden ayudar.

**Comment by sierisimo** [comment]
Estamos a 3 semanas del evento!!!

**Comment by fercho1908** [comment]
El jueves se republico el evento en la pagina del GDG y en otros grupos. :)

**Comment by DavidBarboza** [comment]
Todo listo para el evento hoy!

**Comment by fercho1908** [comment]
Se dio el mayor empuje posible en redes sociales y hoy se recibio el ultimo recordatorio por correo, con datos del evento de Facebook al parecer hay una buena respuesta de la comunidad esperemos que se vea reflejado el dia de hoy, asi que creo que se puede cerrar el issue.
