### ISSUE TITLE
Follow up Realm Event

### ISSUE THREAD

**Issue by IsabelPalomar** [GDLActivity/GDL-Meetup#2]

**Comment by sierisimo** [comment]
Es posible que exportemos un excel/pdf de la gente que "preregistro"?

**Comment by IsabelPalomar** [comment]
Si, voy a hacer el export de los datos y se los mando!

**Comment by IsabelPalomar** [comment]
@lalongooo @sierisimo email sent!

**Comment by IsabelPalomar** [comment]
Waiting for Realm's response

**Comment by lalongooo** [comment]
Ya recibi el correo

**Comment by IsabelPalomar** [comment]
Waiting for Realm's response

**Comment by IsabelPalomar** [comment]
Status: Waiting for confirmation dates to start contacting the venue and promoting the event. It is happening! :D

**Comment by IsabelPalomar** [comment]
Realm envio respuesta con fecha tentativa del 18 de Octubre, esperando confirmacion para contactar a Centraal para patrocinio del espacio

**Comment by sierisimo** [comment]
Envie el correo a Tatiana de Centraal, esperando mensaje de ella para confirmar todo al 100%

**Comment by IsabelPalomar** [comment]
Espacio confirmado! :D

**Comment by IsabelPalomar** [comment]
El siguiente paso es enviar correo (#14) y publicar en las redes sociales la informacion :D

**Comment by lalongooo** [comment]
tienen en mente algo "especial" para dar a conocer el evento o..simiplemente compartimos el link como lo hicimos para el pre-registro?

**Comment by sierisimo** [comment]
No tengo nada pensado, pero seria bueno hacer un evento en facebook, creo que tiene un poco mas de alcance que una publicacion. Igual tambien hacemos las publicaciones ¯\_(ツ)_/¯
Pero todo se manejara por eventbrite, supongo.

**Comment by IsabelPalomar** [comment]
@lalongooo @sierisimo escribi algo de texto para la publicacion del evento, revisenlo y me dan sus comentarios.
* El primero es un texto para enviar a los registrados en el splashthat (splashthat tiene opcion para enviar correo masivo)
* El segundo se puede utilizar en fb o para enviar correo a los integrantes de meetup
 *El tercero es para twitter :) https://docs.google.com/document/d/1xhaigdNegR6Y7v_VN7aF7W-5BBfNco3ppfEg6InHvsE/edit?usp=sharing

**Comment by sierisimo** [comment]
Hoy el meetup es en Centraal, espero Tatiana este ahi, para platicas mas en concreto lo que se quedo dicho/preguntado en el ultimo correo enviado

**Comment by IsabelPalomar** [comment]
Email enviado (7 de Septiembre) a Tracy con la dirección de EPAM para que realicen el envío de las playeras

**Comment by sierisimo** [comment]
Algun dato sobre como vamos de asistencia?
