### ISSUE TITLE
Patrocinio Meetup Octubre

### ISSUE THREAD

**Issue by sierisimo** [GDLActivity/GDL-Meetup#20]
Hay que empezar a acercanos con la gente que puede patrocinar el evento de Octubre y ver que opciones tenemos.

**Comment by DavidBarboza** [comment]
Qué clase de patrocinio necesitamos? Ya tenemos lugar?

**Comment by lalongooo** [comment]
Creo que el patrocinio involucra:
- Lugar
- Pizza/Tacos/Burgers/etc
- Cheve
- Speakers

confirma @sierisimo

**Comment by raul-aponte** [comment]
Se contacto a la administración del seven, estaré a la espera de respuesta, el problema es que si se hace en el centro del software esta difícil meter cerveza :(

**Comment by IsabelPalomar** [comment]
pues que sea limonada jajaja

**Comment by lalongooo** [comment]
Que sea arroz con leche

**Comment by sierisimo** [comment]
Confirmando (bien a tiempo, como siempre):

* Lugar
* Pizza/Tacos/Burgers/etc
* Cheve

Con eso consideramos el patrocinio. Si el patrocinador quiere agregar algo mas, sin bronca.
En los ultimos eventos he visto que con entre 2000 y 2500 sale muy bien (Considerando el numero de asistentes entre 20 y 30)

**Comment by raul-aponte** [comment]
No hubo respuesta por parte de nuestra empresa, creo que seria bueno ir contactando otras opciones, en octubre es aniversario del CSW y es posible que no tengan salones disponibles.

**Comment by sierisimo** [comment]
Tuvimos conflicto para conseguir sponsor ademas que se aproxima el evento de Realm por lo que el meetup de este mes se cancela y le daremos mayor empuje al evento de Realm
