### ISSUE TITLE
Participation GDG Peru (DroidLatino)

### ISSUE THREAD

**Issue by IsabelPalomar** [GDLActivity/GDL-Meetup#5]

**Comment by lalongooo** [comment]
@IsabelPalomar, ¿conseguiste el correo de este chavo organizador de GDG Peru? No recuerdo.

**Comment by IsabelPalomar** [comment]
Le mande los datos de contacto tuyos y de @sierisimo, voy a preguntarle que ha pasado con eso, por lo tanto si gustan pueden agregarlo en FB: https://www.facebook.com/eduardo.jose.medina.alfaro

**Comment by lalongooo** [comment]
Ja! Ya me agregó a Facebook.

**Comment by sierisimo** [comment]
Tambien me agrego en facebook, supongo que queda en el los siguientes pasos.

**Comment by lalongooo** [comment]
Yo le doy seguimiento.
