### ISSUE TITLE
Speakers meetup Septiembre

### ISSUE THREAD

**Issue by IsabelPalomar** [GDLActivity/GDL-Meetup#8]

**Comment by IsabelPalomar** [comment]
Voy a empezar a preguntar quien quiere participar para el siguiente meetup. Alguien se ha apuntado hasta ahora @lalongooo @sierisimo?

**Comment by sierisimo** [comment]
Tengo a un posible speaker que conoci en el wizeline academy, le compartieron mis datos, si no me contacta mañana, me acerco con Nicole de Wizeline y le pido contacto.

**Comment by lalongooo** [comment]
Nope, apenas estoy contactando.

**Comment by lalongooo** [comment]
Tengo a un amigo de Monterrey que quiere ir a Guadalajara a dar una charla.
¿que fecha es el meetup de Sept? ¿El 6? @sierisimo @IsabelPalomar

**Comment by IsabelPalomar** [comment]
Si @lalongooo el siguiente meetup es el 6

**Comment by lalongooo** [comment]
Estoy contactando speakers, creo que es buena idea poner este issue en "In Progress"

**Comment by lalongooo** [comment]
Bueno, el amigo de Monterrey no puede entre semana. Solo puede los fines de semana

**Comment by IsabelPalomar** [comment]
@lalongooo Yo creo que a tu amigo hay que considerarlo para algún evento que organicemos fin de semana, igual pon sus datos en #9

**Comment by IsabelPalomar** [comment]
ahh ya vi que ahi esta xD
My bad

**Comment by sierisimo** [comment]
Un conocido en Wizeline se propuso, estoy en proceso de conseguir sus datos.
Tambien le pedire ayudar a @DavidBarboza  y  Fer para conseguir speakers.

**Comment by sierisimo** [comment]
Tengo primer speaker:

* Alejandro Molas
* Comunicacion ZigBee cifrada con PKI usando Android

**Comment by lalongooo** [comment]
Bueno pues, el amigo de Monterrey solo puede los fines de semana
y el de Luxoft que se anima para el meetup de Octubre, no para Septiembre.
Anotate un Item para los speakers de Octubre.

**Comment by sierisimo** [comment]
Meetup anunciado, @fercho1908 consiguio a los dos ponentes de este mes. 
* Arturo Cervantes
* Alejandro Molas
